name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
      with:
        # fetch the git tags for sbt-dynver and sbt-version-policy to work correctly
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java }}
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:1.${{ matrix.java }}
        apps: sbt
    - name: Run tests
      run: sbt tastyMiMa/test
    - name: Run scalafmt check
      run: sbt scalafmtCheck
    - name: Run version policy check
      run: sbt versionPolicyCheck
    - name: Run TASTy-MiMa
      run: sbt tastyMiMaReportIssues
